name: syncro
description: "Syncro - A cross-platform video sync application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  dynamic_color: ^1.7.0
  file_picker: ^10.3.10
  image_picker: ^1.2.1
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  media_kit_libs_windows_video: ^1.0.7
  intl: ^0.19.0
  screen_brightness: ^2.0.1
  volume_controller: ^2.0.7
  web_socket_channel: ^3.0.1
  path_provider: ^2.1.5
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  path: ^1.8.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/binaries/windows/bin/
    - assets/icons/

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/syncro_C_512x512.png"
  adaptive_icon_background: "#07070f"
  adaptive_icon_foreground: "assets/icons/syncro_C_512x512.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/icons/syncro_C_512x512.png"
    icon_size: 256
